/**
 * Parent-o-bot fixture — layers category
 *
 * @ui DIALOG
 *
 * What the script does:
 *  1. Guard (pre-dialog): requires active CompItem and at least one selected layer;
 *     if not met → alert("Please select at least one layer in the active composition.") and
 *     dialog.close().
 *  2. Opens a Window("dialog","Parent-o-bot") with a listbox populated with all layer names.
 *     User selects 1 or 2 layers from the list as parent controllers.
 *  3. On OK (dialog.show() === 1):
 *     a. Enters undo group "Parent-o-bot".
 *     b. For each target (selectedLayers):
 *        - Removes existing "Multi_Parent" effect if present.
 *        - Calls applyFxFromBinary → writes an FFX temp file (fileWrite) then layer.applyPreset(ffxFile).
 *        - Sets effect("Multi_Parent")("Parent 1").setValue(parentLayer1.index).
 *        - If two parents: sets effect("Multi_Parent")("Parent 2").setValue(parentLayer2.index).
 *     c. After all target layers are processed, calls createExpression on Position, Scale,
 *        Rotation, and Opacity for the last currentLayer in scope (note: the script has a
 *        variable scope quirk — createExpression is called outside the per-layer loop but
 *        references `currentLayer` which retains the last value from the loop; the fixture
 *        models the observable operations, not the bug).
 *     d. Ends undo group.
 *
 * Expressions generated by createExpression reference the Multi_Parent pseudo-effect
 * and are built via string concatenation at runtime, making them 'dynamic-unresolved'
 * from a static-analysis perspective.
 */

import { validateFixture } from '../../src/contracts/index.js';

/** @type {import('../../src/contracts/index.js').Fixture} */
const fixture = {
  script: {
    name: 'Parent-o-bot',
    category: 'layers',
    relPath: 'layers/Parent-o-bot.jsx',
    ui: true
  },
  scenarios: [
    // ------------------------------------------------------------------ success
    {
      name: 'success — one target layer, one parent selected in dialog',
      kind: 'success',
      host: {
        appVersion: '25.0',
        project: {
          items: [
            { id: 'item-comp-pob-1', name: 'Rig Comp', typeName: 'Composition' }
          ]
        },
        activeItemId: 'item-comp-pob-1',
        comps: [
          {
            id: 'item-comp-pob-1',
            name: 'Rig Comp',
            width: 1920,
            height: 1080,
            duration: 5,
            frameRate: 30,
            pixelAspect: 1,
            layers: [
              {
                id: 'layer-ctrl',
                index: 1,
                name: 'Controller',
                type: 'Null',
                threeDLayer: false,
                parentId: null,
                inPoint: 0,
                outPoint: 5,
                properties: [
                  {
                    matchName: 'ADBE Transform Group',
                    name: 'Transform',
                    path: 'Transform',
                    propertyValueType: 'NoValue',
                    canSetExpression: false,
                    numProperties: 6,
                    properties: [
                      {
                        matchName: 'ADBE Position',
                        name: 'Position',
                        path: 'Transform/Position',
                        propertyValueType: 'TwoD',
                        value: [960, 540],
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Scale',
                        name: 'Scale',
                        path: 'Transform/Scale',
                        propertyValueType: 'TwoD',
                        value: [100, 100],
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Rotate Z',
                        name: 'Rotation',
                        path: 'Transform/Rotation',
                        propertyValueType: 'OneD',
                        value: 0,
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Opacity',
                        name: 'Opacity',
                        path: 'Transform/Opacity',
                        propertyValueType: 'OneD',
                        value: 100,
                        canSetExpression: true
                      }
                    ]
                  }
                ]
              },
              {
                id: 'layer-target',
                index: 2,
                name: 'Target Shape',
                type: 'Shape',
                threeDLayer: false,
                parentId: null,
                inPoint: 0,
                outPoint: 5,
                properties: [
                  {
                    matchName: 'ADBE Transform Group',
                    name: 'Transform',
                    path: 'Transform',
                    propertyValueType: 'NoValue',
                    canSetExpression: false,
                    numProperties: 6,
                    properties: [
                      {
                        matchName: 'ADBE Position',
                        name: 'Position',
                        path: 'Transform/Position',
                        propertyValueType: 'TwoD',
                        value: [400, 300],
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Scale',
                        name: 'Scale',
                        path: 'Transform/Scale',
                        propertyValueType: 'TwoD',
                        value: [100, 100],
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Rotate Z',
                        name: 'Rotation',
                        path: 'Transform/Rotation',
                        propertyValueType: 'OneD',
                        value: 0,
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Opacity',
                        name: 'Opacity',
                        path: 'Transform/Opacity',
                        propertyValueType: 'OneD',
                        value: 100,
                        canSetExpression: true
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ],
        // "Target Shape" is the selected target layer
        selection: {
          layerIds: ['layer-target'],
          propertyPaths: []
        }
      },
      actions: [
        // Dialog opens — select "Controller" (index 0 in listbox) as the parent
        { type: 'select', target: 'layerList', value: 0 },
        // Click OK
        { type: 'click', target: 'ok' },
        { type: 'run' }
      ],
      expectedOperations: [
        { kind: 'beginUndoGroup' },
        // applyFxFromBinary: writes FFX temp file then calls applyPreset
        { kind: 'fileWrite' },
        { kind: 'applyPreset' },
        // Set Parent 1 effect value to the controller layer index
        { kind: 'setValue', target: 'Multi_Parent/Parent 1' },
        // Expressions set on all four transform properties of the target layer
        { kind: 'setExpression', target: 'Transform/Position' },
        { kind: 'setExpression', target: 'Transform/Scale' },
        { kind: 'setExpression', target: 'Transform/Rotation' },
        { kind: 'setExpression', target: 'Transform/Opacity' },
        { kind: 'endUndoGroup' }
      ],
      // Expressions are built via string concatenation → dynamic-unresolved from static analysis
      expectedExpressions: [
        {
          targetPath: 'Transform/Position',
          source: 'literal',
          parseStatus: 'dynamic-unresolved'
        },
        {
          targetPath: 'Transform/Scale',
          source: 'literal',
          parseStatus: 'dynamic-unresolved'
        },
        {
          targetPath: 'Transform/Rotation',
          source: 'literal',
          parseStatus: 'dynamic-unresolved'
        },
        {
          targetPath: 'Transform/Opacity',
          source: 'literal',
          parseStatus: 'dynamic-unresolved'
        }
      ],
      // medium: applyPreset requires AE to actually load the binary FFX
      expectedConfidence: 'medium'
    },

    // ------------------------------------------------------------------ success two parents
    {
      name: 'success — one target layer, two parents selected in dialog',
      kind: 'success',
      host: {
        appVersion: '25.0',
        project: {
          items: [
            { id: 'item-comp-pob-2', name: 'Two Parent Comp', typeName: 'Composition' }
          ]
        },
        activeItemId: 'item-comp-pob-2',
        comps: [
          {
            id: 'item-comp-pob-2',
            name: 'Two Parent Comp',
            width: 1920,
            height: 1080,
            duration: 5,
            frameRate: 30,
            pixelAspect: 1,
            layers: [
              {
                id: 'layer-p1',
                index: 1,
                name: 'Parent One',
                type: 'Null',
                threeDLayer: false,
                parentId: null,
                inPoint: 0,
                outPoint: 5,
                properties: []
              },
              {
                id: 'layer-p2',
                index: 2,
                name: 'Parent Two',
                type: 'Null',
                threeDLayer: false,
                parentId: null,
                inPoint: 0,
                outPoint: 5,
                properties: []
              },
              {
                id: 'layer-child',
                index: 3,
                name: 'Child Layer',
                type: 'AV',
                threeDLayer: false,
                parentId: null,
                inPoint: 0,
                outPoint: 5,
                properties: [
                  {
                    matchName: 'ADBE Transform Group',
                    name: 'Transform',
                    path: 'Transform',
                    propertyValueType: 'NoValue',
                    canSetExpression: false,
                    numProperties: 6,
                    properties: [
                      {
                        matchName: 'ADBE Position',
                        name: 'Position',
                        path: 'Transform/Position',
                        propertyValueType: 'TwoD',
                        value: [400, 300],
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Scale',
                        name: 'Scale',
                        path: 'Transform/Scale',
                        propertyValueType: 'TwoD',
                        value: [100, 100],
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Rotate Z',
                        name: 'Rotation',
                        path: 'Transform/Rotation',
                        propertyValueType: 'OneD',
                        value: 0,
                        canSetExpression: true
                      },
                      {
                        matchName: 'ADBE Opacity',
                        name: 'Opacity',
                        path: 'Transform/Opacity',
                        propertyValueType: 'OneD',
                        value: 100,
                        canSetExpression: true
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ],
        selection: {
          layerIds: ['layer-child'],
          propertyPaths: []
        }
      },
      actions: [
        // Select both parent layers (indices 0 and 1) in the listbox
        { type: 'select', target: 'layerList', value: [0, 1] },
        { type: 'click', target: 'ok' },
        { type: 'run' }
      ],
      expectedOperations: [
        { kind: 'beginUndoGroup' },
        { kind: 'fileWrite' },
        { kind: 'applyPreset' },
        { kind: 'setValue', target: 'Multi_Parent/Parent 1' },
        { kind: 'setValue', target: 'Multi_Parent/Parent 2' },
        { kind: 'setExpression', target: 'Transform/Position' },
        { kind: 'setExpression', target: 'Transform/Scale' },
        { kind: 'setExpression', target: 'Transform/Rotation' },
        { kind: 'setExpression', target: 'Transform/Opacity' },
        { kind: 'endUndoGroup' }
      ],
      expectedExpressions: [
        { targetPath: 'Transform/Position', source: 'literal', parseStatus: 'dynamic-unresolved' },
        { targetPath: 'Transform/Scale',    source: 'literal', parseStatus: 'dynamic-unresolved' },
        { targetPath: 'Transform/Rotation', source: 'literal', parseStatus: 'dynamic-unresolved' },
        { targetPath: 'Transform/Opacity',  source: 'literal', parseStatus: 'dynamic-unresolved' }
      ],
      expectedConfidence: 'medium'
    },

    // ------------------------------------------------------------------ guard: no active comp
    {
      name: 'guard — no active composition',
      kind: 'guard',
      host: {
        appVersion: '25.0',
        project: { items: [] },
        activeItemId: null,
        comps: [],
        selection: { layerIds: [], propertyPaths: [] }
      },
      actions: [
        { type: 'run' }
      ],
      expectedOperations: [],
      expectedAlerts: ['Please select at least one layer in the active composition.'],
      expectedConfidence: 'high'
    },

    // ------------------------------------------------------------------ guard: no selected layers
    {
      name: 'guard — active comp but no layers selected',
      kind: 'guard',
      host: {
        appVersion: '25.0',
        project: {
          items: [
            { id: 'item-comp-pob-3', name: 'Idle Comp', typeName: 'Composition' }
          ]
        },
        activeItemId: 'item-comp-pob-3',
        comps: [
          {
            id: 'item-comp-pob-3',
            name: 'Idle Comp',
            width: 1920,
            height: 1080,
            duration: 5,
            frameRate: 30,
            pixelAspect: 1,
            layers: [
              {
                id: 'layer-idle',
                index: 1,
                name: 'Idle Layer',
                type: 'AV',
                threeDLayer: false,
                parentId: null,
                inPoint: 0,
                outPoint: 5,
                properties: []
              }
            ]
          }
        ],
        selection: { layerIds: [], propertyPaths: [] }
      },
      actions: [
        { type: 'run' }
      ],
      expectedOperations: [],
      expectedAlerts: ['Please select at least one layer in the active composition.'],
      expectedConfidence: 'high'
    }
  ]
};

// Self-validate at module load time — throw immediately if contract is violated.
const validation = validateFixture(fixture);
if (!validation.ok) {
  throw new Error(`Parent-o-bot.fixture.js failed contract validation:\n${validation.errors.join('\n')}`);
}

export default fixture;
